let STATE=null;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]));const pct=v=>Math.round((v||0)*100)+'%';const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
async function loadData(){try{const r=await fetch('./data/golf-data.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);STATE=await r.json();$('loadStatus').textContent=`Loaded ${STATE.matches.length} match records and ${STATE.betterball.length} Betterball records.`;initialise()}catch(err){$('loadStatus').classList.add('error');$('loadStatus').innerHTML='Could not load <b>data/golf-data.json</b>. Use GitHub Pages or a local web server. Error: '+esc(err.message)}}
function seasonValues(){return ['ALL',...Array.from(new Set([...STATE.matches.map(x=>String(x.season)),...STATE.betterball.map(x=>String(x.season))])).sort((a,b)=>Number(b)-Number(a))]}
function fillSeason(id){$(id).innerHTML=seasonValues().map(s=>`<option value="${s}">${s==='ALL'?'All Seasons':s}</option>`).join('')}
function playersForSeason(season,source='matches'){if(season==='ALL')return [...STATE.players];const set=new Set();if(source==='betterball'){STATE.betterball.filter(x=>String(x.season)===String(season)).forEach(x=>[x.t1p1,x.t1p2,x.t2p1,x.t2p2].forEach(p=>{if(p)set.add(p)}))}else{STATE.matches.filter(x=>String(x.season)===String(season)).forEach(x=>{if(x.player)set.add(x.player)})}return STATE.players.filter(p=>set.has(p))}
function setPlayers(id,season,index=0){const el=$(id),values=playersForSeason(season),old=el.value;el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(old&&values.includes(old))el.value=old;else if(values.length)el.value=values[index%values.length]}
function playerStats(player,season){const m=STATE.matches.filter(x=>x.player===player&&(season==='ALL'||String(x.season)===String(season))),pts=m.map(x=>Number(x.points)||0);const c=(r,t)=>m.filter(x=>x.result===r&&(!t||x.type===t)).length,singles=m.filter(x=>x.type==='S').length,bb=m.filter(x=>x.type==='BB').length;return{matches:m.length,total:pts.reduce((a,b)=>a+b,0),average:avg(pts),best:pts.length?Math.max(...pts):0,low:pts.length?Math.min(...pts):0,wins:c('W'),draws:c('D'),losses:c('L'),winPct:m.length?c('W')/m.length:0,singlesWinPct:singles?c('W','S')/singles:0,bbWinPct:bb?c('W','BB')/bb:0}}
function drawBars(labels,values){const c=$('chart'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const p=40,m=Math.max(1,...values),bw=(w-p*2)/values.length*.55;x.font='13px Arial';x.textAlign='center';values.forEach((v,i)=>{const cx=p+(i+.5)*(w-p*2)/values.length,bh=(h-p*2)*(v/m);x.fillStyle='#4f8f38';x.fillRect(cx-bw/2,h-p-bh,bw,bh);x.fillStyle='#222';x.fillText(v,cx,h-p-bh-7);x.fillText(labels[i],cx,h-14)})}
function refreshDashboardPlayer(){const s=$('dashSeason').value;setPlayers('player',s,0);const vals=playersForSeason(s);if(vals.includes('Gersh')&&!$('player').dataset.init){$('player').value='Gersh';$('player').dataset.init='1'}}
function renderDashboard(){const season=$('dashSeason').value,p=$('player').value,s=playerStats(p,season);$('cards').innerHTML=[['Matches',s.matches],['Total Points',s.total],['Average Points',s.average.toFixed(1)],['Best',s.best],['Wins',s.wins],['Draws',s.draws],['Losses',s.losses],['Win %',pct(s.winPct)]].map(v=>`<div class="card metric"><div class="label">${v[0]}</div><div class="value">${v[1]}</div></div>`).join('');const rows=STATE.matches.filter(x=>x.player===p&&(season==='ALL'||String(x.season)===String(season)));$('history').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.course)}</td><td>${esc(x.date)}</td><td>${esc(x.opposition)}</td><td>${x.points}</td><td>${esc(x.type)}</td><td class="result-${x.result}">${esc(x.result)}</td><td>${esc(x.cart)}</td></tr>`).join(''):'<tr><td colspan="7">No matches for this player/season.</td></tr>';drawBars(['Wins','Draws','Losses'],[s.wins,s.draws,s.losses])}
function pairingRows(){const season=$('bbSeason').value,out=[];STATE.betterball.filter(x=>season==='ALL'||String(x.season)===String(season)).forEach(x=>{if(x.t1p1&&x.t1p2)out.push({course:x.course,date:x.date,opp:x.opposition,p1:x.t1p1,p2:x.t1p2,score:Number(x.t1combined)||0,result:x.t1result});if(x.t2p1&&x.t2p2)out.push({course:x.course,date:x.date,opp:x.opposition,p1:x.t2p1,p2:x.t2p2,score:Number(x.t2combined)||0,result:x.t2result})});return out}
function renderBetterball(){const rows=pairingRows();$('bbrows').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.course)}</td><td>${esc(x.date)}</td><td>${esc(x.opp)}</td><td>${esc(x.p1)} + ${esc(x.p2)}</td><td>${x.score||''}</td><td class="result-${x.result}">${esc(x.result)}</td></tr>`).join(''):'<tr><td colspan="6">No Betterball results for this season.</td></tr>';const map=new Map();rows.forEach(x=>{const n=[x.p1,x.p2].sort(),k=n.join('|');if(!map.has(k))map.set(k,{name:n.join(' + '),played:0,w:0,d:0,l:0,scores:[]});const a=map.get(k);a.played++;if(x.result==='W')a.w++;else if(x.result==='D')a.d++;else if(x.result==='L')a.l++;if(x.score>0)a.scores.push(x.score)});const ranked=[...map.values()].map(a=>({...a,winPct:a.played?a.w/a.played:0,avg:a.scores.length?avg(a.scores):null,best:a.scores.length?Math.max(...a.scores):null})).sort((a,b)=>b.winPct-a.winPct||((b.avg??-1)-(a.avg??-1))||b.played-a.played);$('bestbb').innerHTML=ranked.map((a,i)=>`<tr><td>${i+1}</td><td><b>${esc(a.name)}</b></td><td>${a.played}</td><td>${a.w}</td><td>${a.d}</td><td>${a.l}</td><td>${pct(a.winPct)}</td><td>${a.avg===null?'—':a.avg.toFixed(1)}</td><td>${a.best===null?'—':a.best}</td></tr>`).join('')}
function refreshComparePlayers(){const season=$('compareSeasonView').value,values=playersForSeason(season);[1,2,3,4,5,6].forEach((n,i)=>{const el=$('p'+n),old=el.value;el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(old&&values.includes(old))el.value=old;else if(values.length)el.value=values[i%values.length]})}
function renderComparison(){const season=$('compareSeasonView').value,ps=[1,2,3,4,5,6].map(i=>$('p'+i).value),ss=ps.map(p=>playerStats(p,season));const rows=[['Matches','matches',v=>v],['Total Points','total',v=>v],['Average Points','average',v=>v.toFixed(1)],['Best Points','best',v=>v],['Lowest Points','low',v=>v],['Wins','wins',v=>v],['Draws','draws',v=>v],['Losses','losses',v=>v],['Win %','winPct',pct],['Singles Win %','singlesWinPct',pct],['Betterball Win %','bbWinPct',pct]];$('compare').innerHTML=rows.map(([l,k,f])=>`<tr><td><b>${l}</b></td>${ss.map(s=>`<td>${f(s[k])}</td>`).join('')}</tr>`).join('')}
function initialise(){['dashSeason','bbSeason','compareSeasonView'].forEach(fillSeason);refreshDashboardPlayer();refreshComparePlayers();$('player').addEventListener('change',renderDashboard);$('dashSeason').addEventListener('change',()=>{refreshDashboardPlayer();renderDashboard()});$('bbSeason').addEventListener('change',renderBetterball);$('compareSeasonView').addEventListener('change',()=>{refreshComparePlayers();renderComparison()});[1,2,3,4,5,6].forEach(n=>$('p'+n).addEventListener('change',renderComparison));document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')}));renderDashboard();renderBetterball();renderComparison()}
loadData();